### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rickdgeerling** [sesamecare/opentelemetry-node-metrics#1]
I'd hazard a guess that the license your package is currently published under is incorrect (otherwise you probably wouldn't publish it)

>Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
>```
>{
>  "license": "UNLICENSED"
>}
>```

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license

**Comment by brianphillips** [comment]
This should be closed (resolved by #2)
